// =============================================================================
// AUTO-GENERATED by SceneScaffoldGenerator from Overworld.unity
// Generated: 2026-04-20 18:37:01
//
// Save:  Tools > Scenes > {SceneName} > Save   (scene → scaffold)
// Load:  Tools > Scenes > {SceneName} > Load   (scaffold → scene)
// =============================================================================

using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Events;
using UnityEngine.EventSystems;
using UnityEditor;
using TMPro;

public static class OverworldScaffold
{
    private const string SceneName = "Overworld";

    // Sprite asset paths
    private const string Sprite_offscreen_arrow = "Assets/Maps/offscreen-arrow.png";
    private const string Sprite_Black32x32 = "Assets/Sprites/Black32x32.png";
    private const string Sprite_Camera00 = "Assets/Sprites/GUI/Camera00.png";

    // Font asset paths
    private const string Font_Attic = "Assets/Fonts/Attic.asset";
    private const string Font_Roboto = "Assets/Fonts/Roboto.asset";
    private const string Font_LiberationSans_SDF = "Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset";

    [MenuItem("Tools/Scenes/Overworld/Load")]
    public static void Load()
    {
        if (!EditorUtility.DisplayDialog("Load",
            "Clear the Overworld scene and recreate all GameObjects from the scaffold?\n\n" +
            "Any unsaved scene changes will be lost.",
            "Load", "Cancel"))
            return;
        if (!SceneScaffoldHelper.OpenScene(SceneName)) return;
        SceneScaffoldHelper.ClearAllRootObjectsSilent();
        CreateScaffolding();
    }

    public static void ClearScene()
    {
        if (!SceneScaffoldHelper.OpenScene(SceneName)) return;
        SceneScaffoldHelper.ClearAllRootObjects();
    }

    public static void CreateScaffolding()
    {
        if (!SceneScaffoldHelper.OpenScene(SceneName)) return;

        // --- BattleTransition ---
        var go_BattleTransition = new GameObject("BattleTransition");
        go_BattleTransition.AddComponent<Scripts.Effects.ScreenGrabber>();
        go_BattleTransition.AddComponent<Scripts.Effects.ZoomEffect>();
        Undo.RegisterCreatedObjectUndo(go_BattleTransition, "Create BattleTransition");

        // --- Bush ---
        var go_Bush = new GameObject("Bush");
        go_Bush.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush, "Create Bush");

        // --- Bush ---
        var go_Bush2 = new GameObject("Bush");
        go_Bush2.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush2, "Create Bush");

        // --- Bush ---
        var go_Bush3 = new GameObject("Bush");
        go_Bush3.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush3, "Create Bush");

        // --- Bush ---
        var go_Bush4 = new GameObject("Bush");
        go_Bush4.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush4, "Create Bush");

        // --- Bush ---
        var go_Bush5 = new GameObject("Bush");
        go_Bush5.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush5, "Create Bush");

        // --- Bush ---
        var go_Bush6 = new GameObject("Bush");
        go_Bush6.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush6, "Create Bush");

        // --- Bush ---
        var go_Bush7 = new GameObject("Bush");
        go_Bush7.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush7, "Create Bush");

        // --- Bush ---
        var go_Bush8 = new GameObject("Bush");
        go_Bush8.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush8, "Create Bush");

        // --- Bush ---
        var go_Bush9 = new GameObject("Bush");
        go_Bush9.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush9, "Create Bush");

        // --- Bush ---
        var go_Bush10 = new GameObject("Bush");
        go_Bush10.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush10, "Create Bush");

        // --- Bush ---
        var go_Bush11 = new GameObject("Bush");
        go_Bush11.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush11, "Create Bush");

        // --- Bush ---
        var go_Bush12 = new GameObject("Bush");
        go_Bush12.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush12, "Create Bush");

        // --- Bush ---
        var go_Bush13 = new GameObject("Bush");
        go_Bush13.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush13, "Create Bush");

        // --- Bush ---
        var go_Bush14 = new GameObject("Bush");
        go_Bush14.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush14, "Create Bush");

        // --- Bush ---
        var go_Bush15 = new GameObject("Bush");
        go_Bush15.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush15, "Create Bush");

        // --- Bush ---
        var go_Bush16 = new GameObject("Bush");
        go_Bush16.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush16, "Create Bush");

        // --- Bush ---
        var go_Bush17 = new GameObject("Bush");
        go_Bush17.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush17, "Create Bush");

        // --- Bush ---
        var go_Bush18 = new GameObject("Bush");
        go_Bush18.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush18, "Create Bush");

        // --- Bush ---
        var go_Bush19 = new GameObject("Bush");
        go_Bush19.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush19, "Create Bush");

        // --- Bush ---
        var go_Bush20 = new GameObject("Bush");
        go_Bush20.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush20, "Create Bush");

        // --- Bush ---
        var go_Bush21 = new GameObject("Bush");
        go_Bush21.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush21, "Create Bush");

        // --- Bush ---
        var go_Bush22 = new GameObject("Bush");
        go_Bush22.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush22, "Create Bush");

        // --- Bush ---
        var go_Bush23 = new GameObject("Bush");
        go_Bush23.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush23, "Create Bush");

        // --- Bush ---
        var go_Bush24 = new GameObject("Bush");
        go_Bush24.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush24, "Create Bush");

        // --- Bush ---
        var go_Bush25 = new GameObject("Bush");
        go_Bush25.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush25, "Create Bush");

        // --- Bush ---
        var go_Bush26 = new GameObject("Bush");
        go_Bush26.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush26, "Create Bush");

        // --- Bush ---
        var go_Bush27 = new GameObject("Bush");
        go_Bush27.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush27, "Create Bush");

        // --- Bush ---
        var go_Bush28 = new GameObject("Bush");
        go_Bush28.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush28, "Create Bush");

        // --- Bush ---
        var go_Bush29 = new GameObject("Bush");
        go_Bush29.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush29, "Create Bush");

        // --- Bush ---
        var go_Bush30 = new GameObject("Bush");
        go_Bush30.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush30, "Create Bush");

        // --- Bush ---
        var go_Bush31 = new GameObject("Bush");
        go_Bush31.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush31, "Create Bush");

        // --- Bush ---
        var go_Bush32 = new GameObject("Bush");
        go_Bush32.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush32, "Create Bush");

        // --- Bush ---
        var go_Bush33 = new GameObject("Bush");
        go_Bush33.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush33, "Create Bush");

        // --- Bush ---
        var go_Bush34 = new GameObject("Bush");
        go_Bush34.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush34, "Create Bush");

        // --- Bush ---
        var go_Bush35 = new GameObject("Bush");
        go_Bush35.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush35, "Create Bush");

        // --- Bush ---
        var go_Bush36 = new GameObject("Bush");
        go_Bush36.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush36, "Create Bush");

        // --- Bush ---
        var go_Bush37 = new GameObject("Bush");
        go_Bush37.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush37, "Create Bush");

        // --- Bush ---
        var go_Bush38 = new GameObject("Bush");
        go_Bush38.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush38, "Create Bush");

        // --- Bush ---
        var go_Bush39 = new GameObject("Bush");
        go_Bush39.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush39, "Create Bush");

        // --- Bush ---
        var go_Bush40 = new GameObject("Bush");
        go_Bush40.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush40, "Create Bush");

        // --- Bush ---
        var go_Bush41 = new GameObject("Bush");
        go_Bush41.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush41, "Create Bush");

        // --- Bush ---
        var go_Bush42 = new GameObject("Bush");
        go_Bush42.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush42, "Create Bush");

        // --- Bush ---
        var go_Bush43 = new GameObject("Bush");
        go_Bush43.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush43, "Create Bush");

        // --- Bush ---
        var go_Bush44 = new GameObject("Bush");
        go_Bush44.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush44, "Create Bush");

        // --- Bush ---
        var go_Bush45 = new GameObject("Bush");
        go_Bush45.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush45, "Create Bush");

        // --- Bush ---
        var go_Bush46 = new GameObject("Bush");
        go_Bush46.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush46, "Create Bush");

        // --- Bush ---
        var go_Bush47 = new GameObject("Bush");
        go_Bush47.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush47, "Create Bush");

        // --- Bush ---
        var go_Bush48 = new GameObject("Bush");
        go_Bush48.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush48, "Create Bush");

        // --- Bush ---
        var go_Bush49 = new GameObject("Bush");
        go_Bush49.AddComponent<Scripts.Overworld.BushInstance>();
        Undo.RegisterCreatedObjectUndo(go_Bush49, "Create Bush");

        // --- Bushes ---
        var go_Bushes = new GameObject("Bushes");
        Undo.RegisterCreatedObjectUndo(go_Bushes, "Create Bushes");

        // --- Canopy ---
        var go_Canopy = new GameObject("Canopy");
        go_Canopy.AddComponent<RectTransform>();
        go_Canopy.AddComponent<CanvasRenderer>();
        go_Canopy.AddComponent<Scripts.Overworld.CanopyInstance>();
        Undo.RegisterCreatedObjectUndo(go_Canopy, "Create Canopy");

        // --- Canvas ---
        var go_Canvas = new GameObject("Canvas");
        go_Canvas.layer = 5;
        go_Canvas.AddComponent<RectTransform>();
        var canvas_Canvas = go_Canvas.AddComponent<Canvas>();
        canvas_Canvas.renderMode = (RenderMode)0;
        go_Canvas.AddComponent<GraphicRaycaster>();
        var scaler_Canvas = go_Canvas.AddComponent<CanvasScaler>();
        scaler_Canvas.uiScaleMode = (CanvasScaler.ScaleMode)0;
        scaler_Canvas.referenceResolution = new Vector2(0f, 0f);
        scaler_Canvas.matchWidthOrHeight = 0f;
        Undo.RegisterCreatedObjectUndo(go_Canvas, "Create Canvas");

        // --- Title ---
        var go_Title = new GameObject("Title");
        go_Title.layer = 5;
        var rt_Title = go_Title.AddComponent<RectTransform>();
        rt_Title.SetParent(go_Canvas.GetComponent<RectTransform>(), false);
        rt_Title.anchorMin = new Vector2(0.5f, 1f);
        rt_Title.anchorMax = new Vector2(0.5f, 1f);
        rt_Title.pivot = new Vector2(0.5f, 0.5f);
        rt_Title.sizeDelta = new Vector2(0f, 0f);
        rt_Title.anchoredPosition = new Vector2(0f, -128f);
        go_Title.AddComponent<CanvasRenderer>();
        var tmp_Title = go_Title.AddComponent<TextMeshProUGUI>();
        tmp_Title.font = SceneScaffoldHelper.LoadFont(Font_Attic);
        tmp_Title.text = "m_isRightToLeft: 0";
        tmp_Title.fontSize = 64f;
        tmp_Title.color = new Color(1f, 1f, 1f, 1f);
        tmp_Title.alignment = (TextAlignmentOptions)258;
        tmp_Title.enableWordWrapping = false;
        tmp_Title.raycastTarget = true;
        Undo.RegisterCreatedObjectUndo(go_Title, "Create Title");

        // --- CameraModeButton ---
        var go_CameraModeButton = new GameObject("CameraModeButton");
        go_CameraModeButton.layer = 5;
        var rt_CameraModeButton = go_CameraModeButton.AddComponent<RectTransform>();
        rt_CameraModeButton.SetParent(go_Canvas.GetComponent<RectTransform>(), false);
        rt_CameraModeButton.anchorMin = new Vector2(1f, 1f);
        rt_CameraModeButton.anchorMax = new Vector2(1f, 1f);
        rt_CameraModeButton.pivot = new Vector2(0.5f, 0.5f);
        rt_CameraModeButton.sizeDelta = new Vector2(64f, 64f);
        rt_CameraModeButton.anchoredPosition = new Vector2(-64f, -126.43f);
        go_CameraModeButton.AddComponent<CanvasRenderer>();
        var img_CameraModeButton = go_CameraModeButton.AddComponent<Image>();
        img_CameraModeButton.sprite = SceneScaffoldHelper.LoadBuiltinSprite();
        img_CameraModeButton.color = new Color(1f, 1f, 1f, 1f);
        img_CameraModeButton.type = (Image.Type)1;
        img_CameraModeButton.raycastTarget = true;
        var btn_CameraModeButton = go_CameraModeButton.AddComponent<Button>();
        btn_CameraModeButton.navigation = new Navigation { mode = (Navigation.Mode)3 };
        btn_CameraModeButton.targetGraphic = go_CameraModeButton.GetComponent<Image>();
        Undo.RegisterCreatedObjectUndo(go_CameraModeButton, "Create CameraModeButton");

        // --- Label ---
        var go_Label = new GameObject("Label");
        go_Label.layer = 5;
        var rt_Label = go_Label.AddComponent<RectTransform>();
        rt_Label.SetParent(go_CameraModeButton.GetComponent<RectTransform>(), false);
        rt_Label.anchorMin = new Vector2(0.5f, 0.5f);
        rt_Label.anchorMax = new Vector2(0.5f, 0.5f);
        rt_Label.pivot = new Vector2(0.5f, 0.5f);
        rt_Label.sizeDelta = new Vector2(200f, 50f);
        rt_Label.anchoredPosition = new Vector2(0f, -43.43f);
        go_Label.AddComponent<CanvasRenderer>();
        var tmp_Label = go_Label.AddComponent<TextMeshProUGUI>();
        tmp_Label.font = SceneScaffoldHelper.LoadFont(Font_Roboto);
        tmp_Label.text = "m_isRightToLeft: 0";
        tmp_Label.fontSize = 20f;
        tmp_Label.color = new Color(1f, 1f, 1f, 1f);
        tmp_Label.alignment = (TextAlignmentOptions)514;
        tmp_Label.enableWordWrapping = true;
        tmp_Label.raycastTarget = true;
        Undo.RegisterCreatedObjectUndo(go_Label, "Create Label");

        // --- Image ---
        var go_Image2 = new GameObject("Image");
        go_Image2.layer = 5;
        var rt_Image2 = go_Image2.AddComponent<RectTransform>();
        rt_Image2.SetParent(go_CameraModeButton.GetComponent<RectTransform>(), false);
        rt_Image2.anchorMin = new Vector2(0.5f, 0.5f);
        rt_Image2.anchorMax = new Vector2(0.5f, 0.5f);
        rt_Image2.pivot = new Vector2(0.5f, 0.5f);
        rt_Image2.sizeDelta = new Vector2(48f, 48f);
        rt_Image2.anchoredPosition = new Vector2(0f, 0f);
        go_Image2.AddComponent<CanvasRenderer>();
        var img_Image2 = go_Image2.AddComponent<Image>();
        img_Image2.sprite = SceneScaffoldHelper.LoadSprite(Sprite_Camera00);
        img_Image2.color = new Color(1f, 1f, 1f, 1f);
        img_Image2.raycastTarget = true;
        Undo.RegisterCreatedObjectUndo(go_Image2, "Create Image");

        // --- EnterHubButton ---
        var go_EnterHubButton = new GameObject("EnterHubButton");
        go_EnterHubButton.layer = 5;
        var rt_EnterHubButton = go_EnterHubButton.AddComponent<RectTransform>();
        rt_EnterHubButton.SetParent(go_Canvas.GetComponent<RectTransform>(), false);
        rt_EnterHubButton.anchorMin = new Vector2(0.5f, 0.5f);
        rt_EnterHubButton.anchorMax = new Vector2(0.5f, 0.5f);
        rt_EnterHubButton.pivot = new Vector2(0.5f, 0.5f);
        rt_EnterHubButton.sizeDelta = new Vector2(160f, 30f);
        rt_EnterHubButton.anchoredPosition = new Vector2(0f, 0f);
        go_EnterHubButton.AddComponent<CanvasRenderer>();
        var img_EnterHubButton = go_EnterHubButton.AddComponent<Image>();
        img_EnterHubButton.sprite = SceneScaffoldHelper.LoadBuiltinSprite();
        img_EnterHubButton.color = new Color(1f, 1f, 1f, 1f);
        img_EnterHubButton.type = (Image.Type)1;
        img_EnterHubButton.raycastTarget = true;
        var btn_EnterHubButton = go_EnterHubButton.AddComponent<Button>();
        btn_EnterHubButton.navigation = new Navigation { mode = (Navigation.Mode)3 };
        btn_EnterHubButton.targetGraphic = go_EnterHubButton.GetComponent<Image>();
        Undo.RegisterCreatedObjectUndo(go_EnterHubButton, "Create EnterHubButton");

        // --- Label ---
        var go_Label4 = new GameObject("Label");
        go_Label4.layer = 5;
        var rt_Label4 = go_Label4.AddComponent<RectTransform>();
        rt_Label4.SetParent(go_EnterHubButton.GetComponent<RectTransform>(), false);
        rt_Label4.anchorMin = new Vector2(0f, 0f);
        rt_Label4.anchorMax = new Vector2(1f, 1f);
        rt_Label4.pivot = new Vector2(0.5f, 0.5f);
        rt_Label4.sizeDelta = new Vector2(0f, 0f);
        rt_Label4.anchoredPosition = new Vector2(0f, 0f);
        go_Label4.AddComponent<CanvasRenderer>();
        var tmp_Label4 = go_Label4.AddComponent<TextMeshProUGUI>();
        tmp_Label4.font = SceneScaffoldHelper.LoadFont(Font_LiberationSans_SDF);
        tmp_Label4.text = "Enter";
        tmp_Label4.fontSize = 24f;
        tmp_Label4.color = new Color(0.1960784f, 0.1960784f, 0.1960784f, 1f);
        tmp_Label4.alignment = (TextAlignmentOptions)514;
        tmp_Label4.enableWordWrapping = true;
        tmp_Label4.raycastTarget = true;
        Undo.RegisterCreatedObjectUndo(go_Label4, "Create Label");

        // --- FadeOverlay ---
        var go_FadeOverlay = new GameObject("FadeOverlay");
        go_FadeOverlay.layer = 5;
        var rt_FadeOverlay = go_FadeOverlay.AddComponent<RectTransform>();
        rt_FadeOverlay.SetParent(go_Canvas.GetComponent<RectTransform>(), false);
        rt_FadeOverlay.anchorMin = new Vector2(0f, 0f);
        rt_FadeOverlay.anchorMax = new Vector2(1f, 1f);
        rt_FadeOverlay.pivot = new Vector2(0.5f, 0.5f);
        rt_FadeOverlay.sizeDelta = new Vector2(-371f, -801.7179f);
        rt_FadeOverlay.anchoredPosition = new Vector2(-0.7313232f, 0.7312012f);
        go_FadeOverlay.AddComponent<CanvasRenderer>();
        var img_FadeOverlay = go_FadeOverlay.AddComponent<Image>();
        img_FadeOverlay.sprite = SceneScaffoldHelper.LoadSprite(Sprite_Black32x32);
        img_FadeOverlay.color = new Color(0f, 0f, 0f, 0f);
        img_FadeOverlay.raycastTarget = false;
        go_FadeOverlay.AddComponent<Scripts.Canvas.FadeOverlayInstance>();
        Undo.RegisterCreatedObjectUndo(go_FadeOverlay, "Create FadeOverlay");

        // --- DayNightCycle ---
        var go_DayNightCycle = new GameObject("DayNightCycle");
        go_DayNightCycle.layer = 5;
        var rt_DayNightCycle = go_DayNightCycle.AddComponent<RectTransform>();
        rt_DayNightCycle.SetParent(go_Canvas.GetComponent<RectTransform>(), false);
        rt_DayNightCycle.anchorMin = new Vector2(0f, 0f);
        rt_DayNightCycle.anchorMax = new Vector2(1f, 1f);
        rt_DayNightCycle.pivot = new Vector2(0.5f, 0.5f);
        rt_DayNightCycle.sizeDelta = new Vector2(0f, 0f);
        rt_DayNightCycle.anchoredPosition = new Vector2(0f, 0f);
        go_DayNightCycle.AddComponent<CanvasRenderer>();
        var img_DayNightCycle = go_DayNightCycle.AddComponent<Image>();
        img_DayNightCycle.color = new Color(1f, 0.62f, 0.45f, 0f);
        img_DayNightCycle.raycastTarget = false;
        go_DayNightCycle.AddComponent<Scripts.Canvas.DayNightCycle>();
        Undo.RegisterCreatedObjectUndo(go_DayNightCycle, "Create DayNightCycle");

        // --- ChangeLeaderButton ---
        var go_ChangeLeaderButton = new GameObject("ChangeLeaderButton");
        go_ChangeLeaderButton.layer = 5;
        var rt_ChangeLeaderButton = go_ChangeLeaderButton.AddComponent<RectTransform>();
        rt_ChangeLeaderButton.SetParent(go_Canvas.GetComponent<RectTransform>(), false);
        rt_ChangeLeaderButton.anchorMin = new Vector2(1f, 1f);
        rt_ChangeLeaderButton.anchorMax = new Vector2(1f, 1f);
        rt_ChangeLeaderButton.pivot = new Vector2(0.5f, 0.5f);
        rt_ChangeLeaderButton.sizeDelta = new Vector2(64f, 64f);
        rt_ChangeLeaderButton.anchoredPosition = new Vector2(-136.3f, -126.43f);
        go_ChangeLeaderButton.AddComponent<CanvasRenderer>();
        var img_ChangeLeaderButton = go_ChangeLeaderButton.AddComponent<Image>();
        img_ChangeLeaderButton.sprite = SceneScaffoldHelper.LoadBuiltinSprite();
        img_ChangeLeaderButton.color = new Color(1f, 1f, 1f, 1f);
        img_ChangeLeaderButton.type = (Image.Type)1;
        img_ChangeLeaderButton.raycastTarget = true;
        var btn_ChangeLeaderButton = go_ChangeLeaderButton.AddComponent<Button>();
        btn_ChangeLeaderButton.navigation = new Navigation { mode = (Navigation.Mode)3 };
        btn_ChangeLeaderButton.targetGraphic = go_ChangeLeaderButton.GetComponent<Image>();
        Undo.RegisterCreatedObjectUndo(go_ChangeLeaderButton, "Create ChangeLeaderButton");

        // --- Image ---
        var go_Image = new GameObject("Image");
        go_Image.layer = 5;
        var rt_Image = go_Image.AddComponent<RectTransform>();
        rt_Image.SetParent(go_ChangeLeaderButton.GetComponent<RectTransform>(), false);
        rt_Image.anchorMin = new Vector2(0.5f, 0.5f);
        rt_Image.anchorMax = new Vector2(0.5f, 0.5f);
        rt_Image.pivot = new Vector2(0.5f, 0.5f);
        rt_Image.sizeDelta = new Vector2(48f, 48f);
        rt_Image.anchoredPosition = new Vector2(0f, 0f);
        go_Image.AddComponent<CanvasRenderer>();
        var img_Image = go_Image.AddComponent<Image>();
        img_Image.color = new Color(1f, 1f, 1f, 1f);
        img_Image.raycastTarget = true;
        Undo.RegisterCreatedObjectUndo(go_Image, "Create Image");

        // --- Label ---
        var go_Label2 = new GameObject("Label");
        go_Label2.layer = 5;
        var rt_Label2 = go_Label2.AddComponent<RectTransform>();
        rt_Label2.SetParent(go_ChangeLeaderButton.GetComponent<RectTransform>(), false);
        rt_Label2.anchorMin = new Vector2(0.5f, 0.5f);
        rt_Label2.anchorMax = new Vector2(0.5f, 0.5f);
        rt_Label2.pivot = new Vector2(0.5f, 0.5f);
        rt_Label2.sizeDelta = new Vector2(200f, 50f);
        rt_Label2.anchoredPosition = new Vector2(0f, -43.43f);
        go_Label2.AddComponent<CanvasRenderer>();
        var tmp_Label2 = go_Label2.AddComponent<TextMeshProUGUI>();
        tmp_Label2.font = SceneScaffoldHelper.LoadFont(Font_Roboto);
        tmp_Label2.text = "m_isRightToLeft: 0";
        tmp_Label2.fontSize = 20f;
        tmp_Label2.color = new Color(1f, 1f, 1f, 1f);
        tmp_Label2.alignment = (TextAlignmentOptions)514;
        tmp_Label2.enableWordWrapping = true;
        tmp_Label2.raycastTarget = true;
        Undo.RegisterCreatedObjectUndo(go_Label2, "Create Label");

        // --- CutoutOverlay ---
        var go_CutoutOverlay = new GameObject("CutoutOverlay");
        go_CutoutOverlay.layer = 5;
        var rt_CutoutOverlay = go_CutoutOverlay.AddComponent<RectTransform>();
        rt_CutoutOverlay.SetParent(go_Canvas.GetComponent<RectTransform>(), false);
        rt_CutoutOverlay.anchorMin = new Vector2(0f, 0f);
        rt_CutoutOverlay.anchorMax = new Vector2(1f, 1f);
        rt_CutoutOverlay.pivot = new Vector2(0.5f, 0.5f);
        rt_CutoutOverlay.sizeDelta = new Vector2(0f, 0f);
        rt_CutoutOverlay.anchoredPosition = new Vector2(0.0001220703f, 0f);
        go_CutoutOverlay.AddComponent<Scripts.Canvas.CutoutOverlay>();
        Undo.RegisterCreatedObjectUndo(go_CutoutOverlay, "Create CutoutOverlay");

        // --- Bottom ---
        var go_Bottom = new GameObject("Bottom");
        var rt_Bottom = go_Bottom.AddComponent<RectTransform>();
        rt_Bottom.SetParent(go_CutoutOverlay.GetComponent<RectTransform>(), false);
        rt_Bottom.anchorMin = new Vector2(0f, 0f);
        rt_Bottom.anchorMax = new Vector2(1f, 0f);
        rt_Bottom.pivot = new Vector2(0.5f, 0f);
        rt_Bottom.sizeDelta = new Vector2(0f, 94.15384f);
        rt_Bottom.anchoredPosition = new Vector2(0f, 0f);
        go_Bottom.AddComponent<CanvasRenderer>();
        var img_Bottom = go_Bottom.AddComponent<Image>();
        img_Bottom.sprite = SceneScaffoldHelper.LoadSprite(Sprite_Black32x32);
        img_Bottom.color = new Color(1f, 1f, 1f, 1f);
        img_Bottom.raycastTarget = false;
        go_Bottom.SetActive(false);
        Undo.RegisterCreatedObjectUndo(go_Bottom, "Create Bottom");

        // --- Top ---
        var go_Top = new GameObject("Top");
        var rt_Top = go_Top.AddComponent<RectTransform>();
        rt_Top.SetParent(go_CutoutOverlay.GetComponent<RectTransform>(), false);
        rt_Top.anchorMin = new Vector2(0f, 1f);
        rt_Top.anchorMax = new Vector2(1f, 1f);
        rt_Top.pivot = new Vector2(0.5f, 1f);
        rt_Top.sizeDelta = new Vector2(0f, 130.1538f);
        rt_Top.anchoredPosition = new Vector2(0f, 0f);
        go_Top.AddComponent<CanvasRenderer>();
        var img_Top = go_Top.AddComponent<Image>();
        img_Top.sprite = SceneScaffoldHelper.LoadSprite(Sprite_Black32x32);
        img_Top.color = new Color(1f, 1f, 1f, 1f);
        img_Top.raycastTarget = false;
        Undo.RegisterCreatedObjectUndo(go_Top, "Create Top");

        // --- CenterPane ---
        var go_CenterPane = new GameObject("CenterPane");
        var rt_CenterPane = go_CenterPane.AddComponent<RectTransform>();
        rt_CenterPane.SetParent(go_Top.GetComponent<RectTransform>(), false);
        rt_CenterPane.anchorMin = new Vector2(0.3333333f, 0f);
        rt_CenterPane.anchorMax = new Vector2(0.6666667f, 1f);
        rt_CenterPane.pivot = new Vector2(0.5f, 0.5f);
        rt_CenterPane.sizeDelta = new Vector2(0f, -7.629395E-06f);
        rt_CenterPane.anchoredPosition = new Vector2(0f, 0f);
        var hlg_CenterPane = go_CenterPane.AddComponent<HorizontalLayoutGroup>();
        hlg_CenterPane.spacing = 0f;
        hlg_CenterPane.childAlignment = (TextAnchor)4;
        hlg_CenterPane.childControlWidth = false;
        hlg_CenterPane.childControlHeight = false;
        hlg_CenterPane.childForceExpandWidth = true;
        hlg_CenterPane.childForceExpandHeight = true;
        Undo.RegisterCreatedObjectUndo(go_CenterPane, "Create CenterPane");

        // --- LeftPane ---
        var go_LeftPane = new GameObject("LeftPane");
        var rt_LeftPane = go_LeftPane.AddComponent<RectTransform>();
        rt_LeftPane.SetParent(go_Top.GetComponent<RectTransform>(), false);
        rt_LeftPane.anchorMin = new Vector2(0f, 0f);
        rt_LeftPane.anchorMax = new Vector2(0.3333333f, 1f);
        rt_LeftPane.pivot = new Vector2(0f, 0.5f);
        rt_LeftPane.sizeDelta = new Vector2(0f, 0f);
        rt_LeftPane.anchoredPosition = new Vector2(0f, 0f);
        var hlg_LeftPane = go_LeftPane.AddComponent<HorizontalLayoutGroup>();
        hlg_LeftPane.spacing = 0f;
        hlg_LeftPane.childAlignment = (TextAnchor)4;
        hlg_LeftPane.childControlWidth = false;
        hlg_LeftPane.childControlHeight = false;
        hlg_LeftPane.childForceExpandWidth = true;
        hlg_LeftPane.childForceExpandHeight = true;
        Undo.RegisterCreatedObjectUndo(go_LeftPane, "Create LeftPane");

        // --- RightPane ---
        var go_RightPane = new GameObject("RightPane");
        var rt_RightPane = go_RightPane.AddComponent<RectTransform>();
        rt_RightPane.SetParent(go_Top.GetComponent<RectTransform>(), false);
        rt_RightPane.anchorMin = new Vector2(0.6666667f, 0f);
        rt_RightPane.anchorMax = new Vector2(1f, 1f);
        rt_RightPane.pivot = new Vector2(1f, 0.5f);
        rt_RightPane.sizeDelta = new Vector2(0f, 0f);
        rt_RightPane.anchoredPosition = new Vector2(0f, 0f);
        var hlg_RightPane = go_RightPane.AddComponent<HorizontalLayoutGroup>();
        hlg_RightPane.spacing = 0f;
        hlg_RightPane.childAlignment = (TextAnchor)4;
        hlg_RightPane.childControlWidth = false;
        hlg_RightPane.childControlHeight = false;
        hlg_RightPane.childForceExpandWidth = true;
        hlg_RightPane.childForceExpandHeight = true;
        Undo.RegisterCreatedObjectUndo(go_RightPane, "Create RightPane");

        // --- BackButton ---
        var go_BackButton = new GameObject("BackButton");
        go_BackButton.layer = 5;
        var rt_BackButton = go_BackButton.AddComponent<RectTransform>();
        rt_BackButton.SetParent(go_Canvas.GetComponent<RectTransform>(), false);
        rt_BackButton.anchorMin = new Vector2(0f, 1f);
        rt_BackButton.anchorMax = new Vector2(0f, 1f);
        rt_BackButton.pivot = new Vector2(0.5f, 0.5f);
        rt_BackButton.sizeDelta = new Vector2(64f, 64f);
        rt_BackButton.anchoredPosition = new Vector2(175f, -64f);
        go_BackButton.AddComponent<CanvasRenderer>();
        var img_BackButton = go_BackButton.AddComponent<Image>();
        img_BackButton.color = new Color(1f, 1f, 1f, 0f);
        img_BackButton.raycastTarget = true;
        var btn_BackButton = go_BackButton.AddComponent<Button>();
        btn_BackButton.navigation = new Navigation { mode = (Navigation.Mode)3 };
        btn_BackButton.targetGraphic = go_BackButton.GetComponent<Image>();
        Undo.RegisterCreatedObjectUndo(go_BackButton, "Create BackButton");

        // --- Label ---
        var go_Label3 = new GameObject("Label");
        go_Label3.layer = 5;
        var rt_Label3 = go_Label3.AddComponent<RectTransform>();
        rt_Label3.SetParent(go_BackButton.GetComponent<RectTransform>(), false);
        rt_Label3.anchorMin = new Vector2(0f, 0f);
        rt_Label3.anchorMax = new Vector2(1f, 1f);
        rt_Label3.pivot = new Vector2(0.5f, 0.5f);
        rt_Label3.sizeDelta = new Vector2(-64f, -64f);
        rt_Label3.anchoredPosition = new Vector2(-32f, 32f);
        go_Label3.AddComponent<CanvasRenderer>();
        var tmp_Label3 = go_Label3.AddComponent<TextMeshProUGUI>();
        tmp_Label3.font = SceneScaffoldHelper.LoadFont(Font_Attic);
        tmp_Label3.text = "<";
        tmp_Label3.fontSize = 64f;
        tmp_Label3.color = new Color(1f, 1f, 1f, 1f);
        tmp_Label3.alignment = (TextAlignmentOptions)514;
        tmp_Label3.enableWordWrapping = true;
        tmp_Label3.raycastTarget = true;
        Undo.RegisterCreatedObjectUndo(go_Label3, "Create Label");

        // --- OffscreenArrow ---
        var go_OffscreenArrow = new GameObject("OffscreenArrow");
        go_OffscreenArrow.layer = 5;
        var rt_OffscreenArrow = go_OffscreenArrow.AddComponent<RectTransform>();
        rt_OffscreenArrow.SetParent(go_Canvas.GetComponent<RectTransform>(), false);
        rt_OffscreenArrow.anchorMin = new Vector2(0.5f, 0.5f);
        rt_OffscreenArrow.anchorMax = new Vector2(0.5f, 0.5f);
        rt_OffscreenArrow.pivot = new Vector2(0.5f, 0.5f);
        rt_OffscreenArrow.sizeDelta = new Vector2(32f, 32f);
        rt_OffscreenArrow.anchoredPosition = new Vector2(475f, 100f);
        go_OffscreenArrow.AddComponent<CanvasRenderer>();
        var img_OffscreenArrow = go_OffscreenArrow.AddComponent<Image>();
        img_OffscreenArrow.sprite = SceneScaffoldHelper.LoadSprite(Sprite_offscreen_arrow);
        img_OffscreenArrow.color = new Color(1f, 1f, 1f, 1f);
        img_OffscreenArrow.raycastTarget = false;
        var canvasGroup_OffscreenArrow = go_OffscreenArrow.AddComponent<CanvasGroup>();
        go_OffscreenArrow.AddComponent<Scripts.Overworld.OffscreenArrowIndicator>();
        Undo.RegisterCreatedObjectUndo(go_OffscreenArrow, "Create OffscreenArrow");

        // --- Caravan ---
        var go_Caravan = new GameObject("Caravan");
        go_Caravan.AddComponent<Scripts.Overworld.CaravanInstance>();
        Undo.RegisterCreatedObjectUndo(go_Caravan, "Create Caravan");

        // --- Cloud ---
        var go_Cloud = new GameObject("Cloud");
        go_Cloud.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud, "Create Cloud");

        // --- Cloud ---
        var go_Cloud2 = new GameObject("Cloud");
        go_Cloud2.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud2, "Create Cloud");

        // --- Cloud ---
        var go_Cloud3 = new GameObject("Cloud");
        go_Cloud3.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud3, "Create Cloud");

        // --- Cloud ---
        var go_Cloud4 = new GameObject("Cloud");
        go_Cloud4.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud4, "Create Cloud");

        // --- Cloud ---
        var go_Cloud5 = new GameObject("Cloud");
        go_Cloud5.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud5, "Create Cloud");

        // --- Cloud ---
        var go_Cloud6 = new GameObject("Cloud");
        go_Cloud6.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud6, "Create Cloud");

        // --- Cloud ---
        var go_Cloud7 = new GameObject("Cloud");
        go_Cloud7.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud7, "Create Cloud");

        // --- Cloud ---
        var go_Cloud8 = new GameObject("Cloud");
        go_Cloud8.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud8, "Create Cloud");

        // --- Cloud ---
        var go_Cloud9 = new GameObject("Cloud");
        go_Cloud9.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud9, "Create Cloud");

        // --- Cloud ---
        var go_Cloud10 = new GameObject("Cloud");
        go_Cloud10.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud10, "Create Cloud");

        // --- Cloud ---
        var go_Cloud11 = new GameObject("Cloud");
        go_Cloud11.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud11, "Create Cloud");

        // --- Cloud ---
        var go_Cloud12 = new GameObject("Cloud");
        go_Cloud12.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud12, "Create Cloud");

        // --- Cloud ---
        var go_Cloud13 = new GameObject("Cloud");
        go_Cloud13.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud13, "Create Cloud");

        // --- Cloud ---
        var go_Cloud14 = new GameObject("Cloud");
        go_Cloud14.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud14, "Create Cloud");

        // --- Cloud ---
        var go_Cloud15 = new GameObject("Cloud");
        go_Cloud15.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud15, "Create Cloud");

        // --- Cloud ---
        var go_Cloud16 = new GameObject("Cloud");
        go_Cloud16.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud16, "Create Cloud");

        // --- Cloud ---
        var go_Cloud17 = new GameObject("Cloud");
        go_Cloud17.AddComponent<Scripts.Overworld.CloudInstance>();
        Undo.RegisterCreatedObjectUndo(go_Cloud17, "Create Cloud");

        // --- Clouds ---
        var go_Clouds = new GameObject("Clouds");
        Undo.RegisterCreatedObjectUndo(go_Clouds, "Create Clouds");

        // --- CloudShadow ---
        var go_CloudShadow = new GameObject("CloudShadow");
        go_CloudShadow.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow2 = new GameObject("CloudShadow");
        go_CloudShadow2.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow2, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow3 = new GameObject("CloudShadow");
        go_CloudShadow3.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow3, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow4 = new GameObject("CloudShadow");
        go_CloudShadow4.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow4, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow5 = new GameObject("CloudShadow");
        go_CloudShadow5.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow5, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow6 = new GameObject("CloudShadow");
        go_CloudShadow6.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow6, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow7 = new GameObject("CloudShadow");
        go_CloudShadow7.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow7, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow8 = new GameObject("CloudShadow");
        go_CloudShadow8.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow8, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow9 = new GameObject("CloudShadow");
        go_CloudShadow9.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow9, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow10 = new GameObject("CloudShadow");
        go_CloudShadow10.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow10, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow11 = new GameObject("CloudShadow");
        go_CloudShadow11.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow11, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow12 = new GameObject("CloudShadow");
        go_CloudShadow12.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow12, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow13 = new GameObject("CloudShadow");
        go_CloudShadow13.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow13, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow14 = new GameObject("CloudShadow");
        go_CloudShadow14.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow14, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow15 = new GameObject("CloudShadow");
        go_CloudShadow15.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow15, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow16 = new GameObject("CloudShadow");
        go_CloudShadow16.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow16, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow17 = new GameObject("CloudShadow");
        go_CloudShadow17.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow17, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow18 = new GameObject("CloudShadow");
        go_CloudShadow18.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow18, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow19 = new GameObject("CloudShadow");
        go_CloudShadow19.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow19, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow20 = new GameObject("CloudShadow");
        go_CloudShadow20.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow20, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow21 = new GameObject("CloudShadow");
        go_CloudShadow21.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow21, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow22 = new GameObject("CloudShadow");
        go_CloudShadow22.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow22, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow23 = new GameObject("CloudShadow");
        go_CloudShadow23.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow23, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow24 = new GameObject("CloudShadow");
        go_CloudShadow24.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow24, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow25 = new GameObject("CloudShadow");
        go_CloudShadow25.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow25, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow26 = new GameObject("CloudShadow");
        go_CloudShadow26.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow26, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow27 = new GameObject("CloudShadow");
        go_CloudShadow27.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow27, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow28 = new GameObject("CloudShadow");
        go_CloudShadow28.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow28, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow29 = new GameObject("CloudShadow");
        go_CloudShadow29.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow29, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow30 = new GameObject("CloudShadow");
        go_CloudShadow30.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow30, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow31 = new GameObject("CloudShadow");
        go_CloudShadow31.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow31, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow32 = new GameObject("CloudShadow");
        go_CloudShadow32.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow32, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow33 = new GameObject("CloudShadow");
        go_CloudShadow33.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow33, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow34 = new GameObject("CloudShadow");
        go_CloudShadow34.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow34, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow35 = new GameObject("CloudShadow");
        go_CloudShadow35.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow35, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow36 = new GameObject("CloudShadow");
        go_CloudShadow36.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow36, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow37 = new GameObject("CloudShadow");
        go_CloudShadow37.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow37, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow38 = new GameObject("CloudShadow");
        go_CloudShadow38.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow38, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow39 = new GameObject("CloudShadow");
        go_CloudShadow39.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow39, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow40 = new GameObject("CloudShadow");
        go_CloudShadow40.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow40, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow41 = new GameObject("CloudShadow");
        go_CloudShadow41.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow41, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow42 = new GameObject("CloudShadow");
        go_CloudShadow42.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow42, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow43 = new GameObject("CloudShadow");
        go_CloudShadow43.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow43, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow44 = new GameObject("CloudShadow");
        go_CloudShadow44.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow44, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow45 = new GameObject("CloudShadow");
        go_CloudShadow45.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow45, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow46 = new GameObject("CloudShadow");
        go_CloudShadow46.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow46, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow47 = new GameObject("CloudShadow");
        go_CloudShadow47.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow47, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow48 = new GameObject("CloudShadow");
        go_CloudShadow48.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow48, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow49 = new GameObject("CloudShadow");
        go_CloudShadow49.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow49, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow50 = new GameObject("CloudShadow");
        go_CloudShadow50.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow50, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow51 = new GameObject("CloudShadow");
        go_CloudShadow51.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow51, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow52 = new GameObject("CloudShadow");
        go_CloudShadow52.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow52, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow53 = new GameObject("CloudShadow");
        go_CloudShadow53.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow53, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow54 = new GameObject("CloudShadow");
        go_CloudShadow54.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow54, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow55 = new GameObject("CloudShadow");
        go_CloudShadow55.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow55, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow56 = new GameObject("CloudShadow");
        go_CloudShadow56.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow56, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow57 = new GameObject("CloudShadow");
        go_CloudShadow57.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow57, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow58 = new GameObject("CloudShadow");
        go_CloudShadow58.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow58, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow59 = new GameObject("CloudShadow");
        go_CloudShadow59.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow59, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow60 = new GameObject("CloudShadow");
        go_CloudShadow60.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow60, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow61 = new GameObject("CloudShadow");
        go_CloudShadow61.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow61, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow62 = new GameObject("CloudShadow");
        go_CloudShadow62.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow62, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow63 = new GameObject("CloudShadow");
        go_CloudShadow63.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow63, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow64 = new GameObject("CloudShadow");
        go_CloudShadow64.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow64, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow65 = new GameObject("CloudShadow");
        go_CloudShadow65.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow65, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow66 = new GameObject("CloudShadow");
        go_CloudShadow66.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow66, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow67 = new GameObject("CloudShadow");
        go_CloudShadow67.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow67, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow68 = new GameObject("CloudShadow");
        go_CloudShadow68.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow68, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow69 = new GameObject("CloudShadow");
        go_CloudShadow69.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow69, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow70 = new GameObject("CloudShadow");
        go_CloudShadow70.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow70, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow71 = new GameObject("CloudShadow");
        go_CloudShadow71.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow71, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow72 = new GameObject("CloudShadow");
        go_CloudShadow72.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow72, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow73 = new GameObject("CloudShadow");
        go_CloudShadow73.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow73, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow74 = new GameObject("CloudShadow");
        go_CloudShadow74.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow74, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow75 = new GameObject("CloudShadow");
        go_CloudShadow75.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow75, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow76 = new GameObject("CloudShadow");
        go_CloudShadow76.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow76, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow77 = new GameObject("CloudShadow");
        go_CloudShadow77.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow77, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow78 = new GameObject("CloudShadow");
        go_CloudShadow78.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow78, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow79 = new GameObject("CloudShadow");
        go_CloudShadow79.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow79, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow80 = new GameObject("CloudShadow");
        go_CloudShadow80.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow80, "Create CloudShadow");

        // --- CloudShadow ---
        var go_CloudShadow81 = new GameObject("CloudShadow");
        go_CloudShadow81.AddComponent<Scripts.Overworld.CloudShadowInstance>();
        Undo.RegisterCreatedObjectUndo(go_CloudShadow81, "Create CloudShadow");

        // --- CloudShadows ---
        var go_CloudShadows = new GameObject("CloudShadows");
        Undo.RegisterCreatedObjectUndo(go_CloudShadows, "Create CloudShadows");

        // --- EventSystem ---
        var go_EventSystem = new GameObject("EventSystem");
        go_EventSystem.AddComponent<StandaloneInputModule>();
        go_EventSystem.AddComponent<EventSystem>();
        Undo.RegisterCreatedObjectUndo(go_EventSystem, "Create EventSystem");

        // --- FishingSpot ---
        var go_FishingSpot = new GameObject("FishingSpot");
        go_FishingSpot.AddComponent<RectTransform>();
        go_FishingSpot.AddComponent<CanvasRenderer>();
        go_FishingSpot.AddComponent<Scripts.Canvas.MapIcon>();
        go_FishingSpot.SetActive(false);
        Undo.RegisterCreatedObjectUndo(go_FishingSpot, "Create FishingSpot");

        // --- Grass ---
        var go_Grass = new GameObject("Grass");
        go_Grass.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass, "Create Grass");

        // --- Grass ---
        var go_Grass2 = new GameObject("Grass");
        go_Grass2.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass2, "Create Grass");

        // --- Grass ---
        var go_Grass3 = new GameObject("Grass");
        go_Grass3.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass3, "Create Grass");

        // --- Grass ---
        var go_Grass4 = new GameObject("Grass");
        go_Grass4.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass4, "Create Grass");

        // --- Grass ---
        var go_Grass5 = new GameObject("Grass");
        go_Grass5.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass5, "Create Grass");

        // --- Grass ---
        var go_Grass6 = new GameObject("Grass");
        go_Grass6.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass6, "Create Grass");

        // --- Grass ---
        var go_Grass7 = new GameObject("Grass");
        go_Grass7.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass7, "Create Grass");

        // --- Grass ---
        var go_Grass8 = new GameObject("Grass");
        go_Grass8.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass8, "Create Grass");

        // --- Grass ---
        var go_Grass9 = new GameObject("Grass");
        go_Grass9.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass9, "Create Grass");

        // --- Grass ---
        var go_Grass10 = new GameObject("Grass");
        go_Grass10.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass10, "Create Grass");

        // --- Grass ---
        var go_Grass11 = new GameObject("Grass");
        go_Grass11.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass11, "Create Grass");

        // --- Grass ---
        var go_Grass12 = new GameObject("Grass");
        go_Grass12.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass12, "Create Grass");

        // --- Grass ---
        var go_Grass13 = new GameObject("Grass");
        go_Grass13.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass13, "Create Grass");

        // --- Grass ---
        var go_Grass14 = new GameObject("Grass");
        go_Grass14.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass14, "Create Grass");

        // --- Grass ---
        var go_Grass15 = new GameObject("Grass");
        go_Grass15.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass15, "Create Grass");

        // --- Grass ---
        var go_Grass16 = new GameObject("Grass");
        go_Grass16.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass16, "Create Grass");

        // --- Grass ---
        var go_Grass17 = new GameObject("Grass");
        go_Grass17.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass17, "Create Grass");

        // --- Grass ---
        var go_Grass18 = new GameObject("Grass");
        go_Grass18.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass18, "Create Grass");

        // --- Grass ---
        var go_Grass19 = new GameObject("Grass");
        go_Grass19.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass19, "Create Grass");

        // --- Grass ---
        var go_Grass20 = new GameObject("Grass");
        go_Grass20.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass20, "Create Grass");

        // --- Grass ---
        var go_Grass21 = new GameObject("Grass");
        go_Grass21.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass21, "Create Grass");

        // --- Grass ---
        var go_Grass22 = new GameObject("Grass");
        go_Grass22.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass22, "Create Grass");

        // --- Grass ---
        var go_Grass23 = new GameObject("Grass");
        go_Grass23.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass23, "Create Grass");

        // --- Grass ---
        var go_Grass24 = new GameObject("Grass");
        go_Grass24.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass24, "Create Grass");

        // --- Grass ---
        var go_Grass25 = new GameObject("Grass");
        go_Grass25.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass25, "Create Grass");

        // --- Grass ---
        var go_Grass26 = new GameObject("Grass");
        go_Grass26.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass26, "Create Grass");

        // --- Grass ---
        var go_Grass27 = new GameObject("Grass");
        go_Grass27.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass27, "Create Grass");

        // --- Grass ---
        var go_Grass28 = new GameObject("Grass");
        go_Grass28.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass28, "Create Grass");

        // --- Grass ---
        var go_Grass29 = new GameObject("Grass");
        go_Grass29.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass29, "Create Grass");

        // --- Grass ---
        var go_Grass30 = new GameObject("Grass");
        go_Grass30.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass30, "Create Grass");

        // --- Grass ---
        var go_Grass31 = new GameObject("Grass");
        go_Grass31.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass31, "Create Grass");

        // --- Grass ---
        var go_Grass32 = new GameObject("Grass");
        go_Grass32.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass32, "Create Grass");

        // --- Grass ---
        var go_Grass33 = new GameObject("Grass");
        go_Grass33.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass33, "Create Grass");

        // --- Grass ---
        var go_Grass34 = new GameObject("Grass");
        go_Grass34.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass34, "Create Grass");

        // --- Grass ---
        var go_Grass35 = new GameObject("Grass");
        go_Grass35.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass35, "Create Grass");

        // --- Grass ---
        var go_Grass36 = new GameObject("Grass");
        go_Grass36.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass36, "Create Grass");

        // --- Grass ---
        var go_Grass37 = new GameObject("Grass");
        go_Grass37.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass37, "Create Grass");

        // --- Grass ---
        var go_Grass38 = new GameObject("Grass");
        go_Grass38.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass38, "Create Grass");

        // --- Grass ---
        var go_Grass39 = new GameObject("Grass");
        go_Grass39.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass39, "Create Grass");

        // --- Grass ---
        var go_Grass40 = new GameObject("Grass");
        go_Grass40.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass40, "Create Grass");

        // --- Grass ---
        var go_Grass41 = new GameObject("Grass");
        go_Grass41.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass41, "Create Grass");

        // --- Grass ---
        var go_Grass42 = new GameObject("Grass");
        go_Grass42.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass42, "Create Grass");

        // --- Grass ---
        var go_Grass43 = new GameObject("Grass");
        go_Grass43.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass43, "Create Grass");

        // --- Grass ---
        var go_Grass44 = new GameObject("Grass");
        go_Grass44.AddComponent<Scripts.Overworld.GrassInstance>();
        Undo.RegisterCreatedObjectUndo(go_Grass44, "Create Grass");

        // --- Grasses ---
        var go_Grasses = new GameObject("Grasses");
        Undo.RegisterCreatedObjectUndo(go_Grasses, "Create Grasses");

        // --- Hero_00 ---
        var go_Hero_00 = new GameObject("Hero_00");
        go_Hero_00.AddComponent<CanvasRenderer>();
        go_Hero_00.AddComponent<Scripts.Overworld.OverworldHero>();
        Undo.RegisterCreatedObjectUndo(go_Hero_00, "Create Hero_00");

        // --- Hero_01 ---
        var go_Hero_01 = new GameObject("Hero_01");
        go_Hero_01.AddComponent<CanvasRenderer>();
        go_Hero_01.AddComponent<Scripts.Overworld.OverworldHero>();
        Undo.RegisterCreatedObjectUndo(go_Hero_01, "Create Hero_01");

        // --- Hero_02 ---
        var go_Hero_02 = new GameObject("Hero_02");
        go_Hero_02.AddComponent<CanvasRenderer>();
        go_Hero_02.AddComponent<Scripts.Overworld.OverworldHero>();
        Undo.RegisterCreatedObjectUndo(go_Hero_02, "Create Hero_02");

        // --- Hero_03 ---
        var go_Hero_03 = new GameObject("Hero_03");
        go_Hero_03.AddComponent<CanvasRenderer>();
        go_Hero_03.AddComponent<Scripts.Overworld.OverworldHero>();
        Undo.RegisterCreatedObjectUndo(go_Hero_03, "Create Hero_03");

        // --- Heroes ---
        var go_Heroes = new GameObject("Heroes");
        Undo.RegisterCreatedObjectUndo(go_Heroes, "Create Heroes");

        // --- Main Camera ---
        var go_Main_Camera = new GameObject("Main Camera");
        var cam_Main_Camera = go_Main_Camera.AddComponent<Camera>();
        cam_Main_Camera.orthographic = false;
        cam_Main_Camera.orthographicSize = 5f;
        cam_Main_Camera.depth = -1f;
        cam_Main_Camera.clearFlags = (CameraClearFlags)1;
        cam_Main_Camera.backgroundColor = new Color(0.1921569f, 0.3019608f, 0.4745098f, 0f);
        go_Main_Camera.AddComponent<AudioListener>();
        // TODO: unresolved script GUID=a79441f348de89743a2939f4d699eac1 — component skipped.
        go_Main_Camera.AddComponent<Scripts.Overworld.Mode7CameraController>();
        Undo.RegisterCreatedObjectUndo(go_Main_Camera, "Create Main Camera");

        // --- Map ---
        var go_Map = new GameObject("Map");
        Undo.RegisterCreatedObjectUndo(go_Map, "Create Map");

        // --- OverworldManager ---
        var go_OverworldManager = new GameObject("OverworldManager");
        go_OverworldManager.AddComponent<Scripts.Managers.OverworldManager>();
        Undo.RegisterCreatedObjectUndo(go_OverworldManager, "Create OverworldManager");

        // --- Props ---
        var go_Props = new GameObject("Props");
        Undo.RegisterCreatedObjectUndo(go_Props, "Create Props");

        // --- Rock ---
        var go_Rock = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock, "Create Rock");

        // --- Rock ---
        var go_Rock2 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock2, "Create Rock");

        // --- Rock ---
        var go_Rock3 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock3, "Create Rock");

        // --- Rock ---
        var go_Rock4 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock4, "Create Rock");

        // --- Rock ---
        var go_Rock5 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock5, "Create Rock");

        // --- Rock ---
        var go_Rock6 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock6, "Create Rock");

        // --- Rock ---
        var go_Rock7 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock7, "Create Rock");

        // --- Rock ---
        var go_Rock8 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock8, "Create Rock");

        // --- Rock ---
        var go_Rock9 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock9, "Create Rock");

        // --- Rock ---
        var go_Rock10 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock10, "Create Rock");

        // --- Rock ---
        var go_Rock11 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock11, "Create Rock");

        // --- Rock ---
        var go_Rock12 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock12, "Create Rock");

        // --- Rock ---
        var go_Rock13 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock13, "Create Rock");

        // --- Rock ---
        var go_Rock14 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock14, "Create Rock");

        // --- Rock ---
        var go_Rock15 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock15, "Create Rock");

        // --- Rock ---
        var go_Rock16 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock16, "Create Rock");

        // --- Rock ---
        var go_Rock17 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock17, "Create Rock");

        // --- Rock ---
        var go_Rock18 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock18, "Create Rock");

        // --- Rock ---
        var go_Rock19 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock19, "Create Rock");

        // --- Rock ---
        var go_Rock20 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock20, "Create Rock");

        // --- Rock ---
        var go_Rock21 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock21, "Create Rock");

        // --- Rock ---
        var go_Rock22 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock22, "Create Rock");

        // --- Rock ---
        var go_Rock23 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock23, "Create Rock");

        // --- Rock ---
        var go_Rock24 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock24, "Create Rock");

        // --- Rock ---
        var go_Rock25 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock25, "Create Rock");

        // --- Rock ---
        var go_Rock26 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock26, "Create Rock");

        // --- Rock ---
        var go_Rock27 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock27, "Create Rock");

        // --- Rock ---
        var go_Rock28 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock28, "Create Rock");

        // --- Rock ---
        var go_Rock29 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock29, "Create Rock");

        // --- Rock ---
        var go_Rock30 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock30, "Create Rock");

        // --- Rock ---
        var go_Rock31 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock31, "Create Rock");

        // --- Rock ---
        var go_Rock32 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock32, "Create Rock");

        // --- Rock ---
        var go_Rock33 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock33, "Create Rock");

        // --- Rock ---
        var go_Rock34 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock34, "Create Rock");

        // --- Rock ---
        var go_Rock35 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock35, "Create Rock");

        // --- Rock ---
        var go_Rock36 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock36, "Create Rock");

        // --- Rock ---
        var go_Rock37 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock37, "Create Rock");

        // --- Rock ---
        var go_Rock38 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock38, "Create Rock");

        // --- Rock ---
        var go_Rock39 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock39, "Create Rock");

        // --- Rock ---
        var go_Rock40 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock40, "Create Rock");

        // --- Rock ---
        var go_Rock41 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock41, "Create Rock");

        // --- Rock ---
        var go_Rock42 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock42, "Create Rock");

        // --- Rock ---
        var go_Rock43 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock43, "Create Rock");

        // --- Rock ---
        var go_Rock44 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock44, "Create Rock");

        // --- Rock ---
        var go_Rock45 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock45, "Create Rock");

        // --- Rock ---
        var go_Rock46 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock46, "Create Rock");

        // --- Rock ---
        var go_Rock47 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock47, "Create Rock");

        // --- Rock ---
        var go_Rock48 = new GameObject("Rock");
        Undo.RegisterCreatedObjectUndo(go_Rock48, "Create Rock");

        // --- Rocks ---
        var go_Rocks = new GameObject("Rocks");
        go_Rocks.AddComponent<Scripts.Overworld.RockInstance>();
        Undo.RegisterCreatedObjectUndo(go_Rocks, "Create Rocks");

        // --- Soil ---
        var go_Soil = new GameObject("Soil");
        go_Soil.AddComponent<RectTransform>();
        go_Soil.AddComponent<CanvasRenderer>();
        go_Soil.AddComponent<Scripts.Overworld.SoilInstance>();
        Undo.RegisterCreatedObjectUndo(go_Soil, "Create Soil");

        // --- Surface ---
        var go_Surface = new GameObject("Surface");
        go_Surface.AddComponent<RectTransform>();
        go_Surface.AddComponent<CanvasRenderer>();
        Undo.RegisterCreatedObjectUndo(go_Surface, "Create Surface");

        // --- Terrain ---
        var go_Terrain = new GameObject("Terrain");
        go_Terrain.AddComponent<RectTransform>();
        go_Terrain.AddComponent<CanvasRenderer>();
        Undo.RegisterCreatedObjectUndo(go_Terrain, "Create Terrain");

        // --- Tree ---
        var go_Tree = new GameObject("Tree");
        go_Tree.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree, "Create Tree");

        // --- Tree ---
        var go_Tree2 = new GameObject("Tree");
        go_Tree2.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree2, "Create Tree");

        // --- Tree ---
        var go_Tree3 = new GameObject("Tree");
        go_Tree3.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree3, "Create Tree");

        // --- Tree ---
        var go_Tree4 = new GameObject("Tree");
        go_Tree4.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree4, "Create Tree");

        // --- Tree ---
        var go_Tree5 = new GameObject("Tree");
        go_Tree5.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree5, "Create Tree");

        // --- Tree ---
        var go_Tree6 = new GameObject("Tree");
        go_Tree6.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree6, "Create Tree");

        // --- Tree ---
        var go_Tree7 = new GameObject("Tree");
        go_Tree7.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree7, "Create Tree");

        // --- Tree ---
        var go_Tree8 = new GameObject("Tree");
        go_Tree8.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree8, "Create Tree");

        // --- Tree ---
        var go_Tree9 = new GameObject("Tree");
        go_Tree9.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree9, "Create Tree");

        // --- Tree ---
        var go_Tree10 = new GameObject("Tree");
        go_Tree10.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree10, "Create Tree");

        // --- Tree ---
        var go_Tree11 = new GameObject("Tree");
        go_Tree11.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree11, "Create Tree");

        // --- Tree ---
        var go_Tree12 = new GameObject("Tree");
        go_Tree12.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree12, "Create Tree");

        // --- Tree ---
        var go_Tree13 = new GameObject("Tree");
        go_Tree13.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree13, "Create Tree");

        // --- Tree ---
        var go_Tree14 = new GameObject("Tree");
        go_Tree14.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree14, "Create Tree");

        // --- Tree ---
        var go_Tree15 = new GameObject("Tree");
        go_Tree15.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree15, "Create Tree");

        // --- Tree ---
        var go_Tree16 = new GameObject("Tree");
        go_Tree16.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree16, "Create Tree");

        // --- Tree ---
        var go_Tree17 = new GameObject("Tree");
        go_Tree17.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree17, "Create Tree");

        // --- Tree ---
        var go_Tree18 = new GameObject("Tree");
        go_Tree18.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree18, "Create Tree");

        // --- Tree ---
        var go_Tree19 = new GameObject("Tree");
        go_Tree19.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree19, "Create Tree");

        // --- Tree ---
        var go_Tree20 = new GameObject("Tree");
        go_Tree20.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree20, "Create Tree");

        // --- Tree ---
        var go_Tree21 = new GameObject("Tree");
        go_Tree21.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree21, "Create Tree");

        // --- Tree ---
        var go_Tree22 = new GameObject("Tree");
        go_Tree22.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree22, "Create Tree");

        // --- Tree ---
        var go_Tree23 = new GameObject("Tree");
        go_Tree23.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree23, "Create Tree");

        // --- Tree ---
        var go_Tree24 = new GameObject("Tree");
        go_Tree24.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree24, "Create Tree");

        // --- Tree ---
        var go_Tree25 = new GameObject("Tree");
        go_Tree25.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree25, "Create Tree");

        // --- Tree ---
        var go_Tree26 = new GameObject("Tree");
        go_Tree26.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree26, "Create Tree");

        // --- Tree ---
        var go_Tree27 = new GameObject("Tree");
        go_Tree27.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree27, "Create Tree");

        // --- Tree ---
        var go_Tree28 = new GameObject("Tree");
        go_Tree28.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree28, "Create Tree");

        // --- Tree ---
        var go_Tree29 = new GameObject("Tree");
        go_Tree29.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree29, "Create Tree");

        // --- Tree ---
        var go_Tree30 = new GameObject("Tree");
        go_Tree30.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree30, "Create Tree");

        // --- Tree ---
        var go_Tree31 = new GameObject("Tree");
        go_Tree31.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree31, "Create Tree");

        // --- Tree ---
        var go_Tree32 = new GameObject("Tree");
        go_Tree32.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree32, "Create Tree");

        // --- Tree ---
        var go_Tree33 = new GameObject("Tree");
        go_Tree33.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree33, "Create Tree");

        // --- Tree ---
        var go_Tree34 = new GameObject("Tree");
        go_Tree34.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree34, "Create Tree");

        // --- Tree ---
        var go_Tree35 = new GameObject("Tree");
        go_Tree35.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree35, "Create Tree");

        // --- Tree ---
        var go_Tree36 = new GameObject("Tree");
        go_Tree36.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree36, "Create Tree");

        // --- Tree ---
        var go_Tree37 = new GameObject("Tree");
        go_Tree37.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree37, "Create Tree");

        // --- Tree ---
        var go_Tree38 = new GameObject("Tree");
        go_Tree38.AddComponent<Scripts.Overworld.TreeInstance>();
        Undo.RegisterCreatedObjectUndo(go_Tree38, "Create Tree");

        // --- Trees ---
        var go_Trees = new GameObject("Trees");
        Undo.RegisterCreatedObjectUndo(go_Trees, "Create Trees");

        // --- onClick event wiring ---
        SceneScaffoldHelper.WireOnClick(
            go_CameraModeButton.GetComponent<Button>(),
            new UnityAction(go_OverworldManager.GetComponent<Scripts.Managers.OverworldManager>().CycleCameraMode));
        SceneScaffoldHelper.WireOnClick(
            go_ChangeLeaderButton.GetComponent<Button>(),
            new UnityAction(go_OverworldManager.GetComponent<Scripts.Managers.OverworldManager>().ChangeLeader));
        // TODO: unresolved onClick — go_BackButton → OverworldManager.OnBackButtonClicked

        UnityEditor.SceneManagement.EditorSceneManager.MarkSceneDirty(
            UnityEditor.SceneManagement.EditorSceneManager.GetActiveScene());
    }
}
