using System;

namespace Assets.Helpers
{
    /// <summary>
    /// CHARACTERCLASS - Actor type identifiers.
    /// 
    /// PURPOSE:
    /// Enum identifying all playable heroes and enemy types in the game.
    /// Used for actor data lookup, sprite loading, and save/load.
    /// 
    /// CATEGORIES:
    /// - Heroes: Paladin, Alchemist, ChromaNinja, etc.
    /// - Enemies: Slime00-03, Wolf00-03, CeramicKnight00-06, etc.
    /// - None: Default/invalid value
    /// 
    /// NAMING CONVENTION:
    /// - Base name: Character archetype (Slime, Wolf, etc.)
    /// - Suffix number: Variant (00 = basic, higher = stronger)
    /// 
    /// USAGE:
    /// ```csharp
    /// var data = ActorLibrary.Get(CharacterClass.Paladin);
    /// var sprite = SpriteLibrary.GetPortrait(CharacterClass.Slime00);
    /// ```
    /// 
    /// RELATED FILES:
    /// - ActorLibrary.cs: Maps to ActorData
    /// - SpriteLibrary.cs: Maps to sprites
    /// - ActorData.cs: Character stats/abilities
    /// </summary>
    public enum CharacterClass
    {
        None = 0,
        Alchemist,
        Assassain,
        Barbarian,
        Basher,
        Bat00,
        Bat01,
        Bat02,
        BlackNinja,
        BlackWitch,
        BlueLion,
        BlueNinja,
        Bruiser,
        Captain,
        CeramicKnight00,
        CeramicKnight01,
        CeramicKnight02,
        CeramicKnight03,
        CeramicKnight04,
        CeramicKnight05,
        CeramicKnight06,
        ChromaNinja,
        Cleric,
        Courier,
        CyberZombie00,
        CyberZombie01,
        CyberZombie02,
        CyberZombie03,
        CyberZombie04,
        Cyclops00,
        Cyclops01,
        Cyclops02,
        Cyclops03,
        Cyclops04,
        Cyclops06,
        DarkTemplar,
        Defender,
        DemonLord,
        Dervish,
        Doctor,
        Drifter,
        Duelist,
        Engineer,
        Fencer,
        Fighter,
        FlyingMonkey,
        Frog00,
        Frog01,
        Frog02,
        Frog03,
        Ganger00,
        Ganger01,
        Ganger02,
        Ganger03,
        Ganger04,
        Ganger05,
        Ganger06,
        Ghost,
        GoblinThug00,
        GreenNinja,
        Hag00,
        Hag01,
        Hag02,
        Hag03,
        Harbinger,
        IceMauler,
        JadeKnight,
        Knight,
        Lancer,
        Lurker00,
        Lurker01,
        Lurker02,
        Machinist,
        Mannequin,
        MarshShambler00,
        MarshShambler01,
        MarshShambler03,
        MartialArtist,
        MechaArmor00,
        MechaArmor01,
        MechaArmor02,
        Monk,
        MountainTroll,
        Myrmidon,
        Naga00,
        NightHunter,
        Odachi,
        Oni00,
        Oni01,
        Oni02,
        Operative,
        Paladin,
        PandaGirl,
        Phantom,
        PrizeFighter,
        Pugilist,
        PurplePrototype00,
        PurplePrototype01,
        PurplePrototype02,
        PurplePrototype03,
        PurplePrototype04,
        Raider,
        Reaper,
        RedMage,
        RedNinja,
        Ripper,
        Ritualist,
        Ronin,
        Sage,
        SandMaw,
        Scorpion,
        Sellsword,
        ShieldMaiden,
        Sister,
        Skelepede00,
        Skelepede01,
        Skelepede02,
        Slasher,
        Slime00,
        Slime01,
        Slime02,
        Slime03,
        Soldier00,
        Soldier01,
        Soldier02,
        Soldier03,
        Speedster,
        SteppinRazor00,
        SteppinRazor01,
        SteppinRazor02,
        SteppinRazor04,
        SteppinRazor05,
        StreetFighter,
        Striker,
        SwampMistress00,
        SwordMaster,
        Tank,
        TechGremlin00,
        TechGremlin01,
        TechGremlin02,
        Technician,
        Templar00,
        Templar01,
        Templar02,
        Templar03,
        Templar04,
        Templar05,
        Thief,
        Tinkerer,
        Toad00,
        TreeGolem00,
        TreeGolem01,
        TreeGolem02,
        TreeGolem03,
        TreeGolem04,
        TreeGolem06,
        Undead00,
        Undead01,
        Undead02,
        Undead04,
        Vampire,
        Vulture,
        WarChief,
        Werewolf00,
        WhiteNinja,
        WhiteWitch,
        WildChild,
        Wolf00,
        Wolf01,
        Wolf02,
        Wolf03,
        YellowNinja,
        Yeti
    }
}
